language: java
jdk:
- oraclejdk8
before_install:
- chmod +x ./gradlew
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: a5gs0JRiCnXvQnbb7j7vJKGpEm9GJmB3yxqhiFBYb5WWvawIFSQnHOAxhkyJQY/64hIJNNnBbNq6kI1EtbUBlIaz0x5pgEScb8q/BIl/WkdrZsol9Mz13nbdj4fuoajnmm9t4LhH3IeE/9k4YYQ0uXKTk3zewihOgD3wWAsmnPWsX5YZHJTF/Siyd/2XdakjeWdgT0K4VdC1oyVgEjEs9YEeICbYKGQD01bf84UryK2W4oNspsutFzfbRrOXVGJmVUS4CvZC8FdhRpnIomVc46Qiuc/0kj40QCEzKkYm41Uu7UudwQWIiCVI+/aRUrJ5H0thPybraOrvHLJe4htY9u4iCvO3hIa9UjJ1VGuaFWQCu1j8e3pCutiCmsxNFCPaTHDcr8iYgd0Prkh9qGrfZ+ldDUJ8Mi4TSVNP2TVqMfTu8lhUkbpAENMtkjSV/opcCWdKeWeuAh7jXewRKCCB665DBLsx0FyQ16N+0FFIGEYL5qamqbBcFK59T1rAj3DXwxhB9ziLnr+q8LKDRNQ2UvtR7gJElix5EWA4RWF9to6bp3FZ/zdHxPHo2MM1ycdaUYZHJVKxbYI4KrW8KQ4W55cmQlOuuzRIJk6IMEtlwYGTwVF8e3zVLiZu2s13dkYkfIDonQATAGns4dRDtmezehLyhf3/3DiSr98z818LV1w=
  app: simplerester
