language: java
jdk:
- oraclejdk8
before_install:
- chmod +x ./gradlew
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: w/QC2ERBskIzrtT2KXoFvc2xixBal7tJ+EAwQH/NfuvKRaacHgPiOR0AcP0MzswjTB9EDuAvsWieDYW4z5gVcaZUr2DJ9B+4CapiBo8eR7dwoYMEiqWiBR4rxaxKa4DWN6Uesmc1L0TKhguS0DlO4nguglweByaOlzyDpND7p0qjidogm4pXY6mmhUWHXAyfHJkZt7wOfDk6CNARSG/nK9b8Ho0C6ugl8litlkdPH1ucVmLPg8XLpTnRs6GU8LvqVCu2DvjTLJ20rBcU2TeGF846Bh3Io8XCaPU3e1ELNM7q/NfzTMBukH9DNZG11zWCr+TEGqo2Ax+V/C8blGMLVBsGiCSTGjV6KzfXhEz/+Dq3SDs/wv9L08Ol3FCYjKZQkEgLLlar9sBRqelSgKw8yG2UYD+lTfkB4ouxNNhgD82YpQiRMms7EQ5+l2fiKG4suCzqRhDHwbgqdj2FKT2Av8pur1w3iOHqhqucFolbwrnwBCfifa5CCtEfAKjl8UuLh7bpxIUYEmbSosSRHSApkUq6B0jF4LfjxHF0yWu/+YjTs8+GpJFQCfKqyZ0upYoSZFmgIjmGvlipun5OBAF1xEl6f3G1xANUaM9erMOLMWqGcArjJ+0zox+Icj8SKlOn2mwov9xmmDrU4KcKwOg17nWD2CvM5ggOIITmdUtTZyk=
  app: simplerester
  on:
    repo: kojisaiki/SimpleRESTer
